version: '3.5'
services:
  web-server:
    image: demo:v01
    container_name: demo_container
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=employee
    ports:
      - '5432:5432'